### ISSUE TITLE
add more js files when build

### ISSUE THREAD

**Issue by chiragkanhasoft** [satendra02/react-chrome-extension#11]
i have added couple of more .js files in src folder. My file name is `contentinjector.js`. Now i also want to create same name file when i build project. where should i make change that it will also create `contentinjector.js` along with `app.js and content.js` in `build/static/js`

**Comment by satendra02** [comment]
Hi @chiragkanhasoft 

 If you want to use some static js file to use in your project you can keep it in the `public` folder.

 `content.js` and `app.js` are the entry point for the extension and web respectively. if you want to create another entry point, follow the same configuration settings done for `content.js` in `webpack.config.prod.js` file inside the `config` folder.

**Comment by chiragkanhasoft** [comment]
Thanks for your answer.
