### ISSUE TITLE
Use google login react library with chrome extension

### ISSUE THREAD

**Issue by chiragkanhasoft** [satendra02/react-chrome-extension#13]
`https://www.npmjs.com/package/react-google-login`

when I try to use this library with your code, it's not working. can you please help me out to solve this issue.

**Comment by satendra02** [comment]
Can you elaborate on your question? What do you mean by not working? Do you have any error log?

**Comment by chiragkanhasoft** [comment]
here I am attaching images.

![image](https://user-images.githubusercontent.com/27885527/71569259-ea077c00-2af3-11ea-9e33-05a3a22d9ae0.png)

here is the error image
![image](https://user-images.githubusercontent.com/27885527/71569262-eecc3000-2af3-11ea-9463-bb27216ce4b7.png)

**Comment by satendra02** [comment]
Hi @chiragkanhasoft 
It is not the issue of this repository. You must look into the `react-google-login` issues section for the same.

I found a similar issue in  `react-google-login` repo. Hope it helps
https://github.com/anthonyjgrove/react-google-login/issues/57

**Comment by sabinbogati1** [comment]
@chiragkanhasoft @satendra02  is this issue fixed? If so how did you fix it ? 
I am also facing similar issue
