### ISSUE TITLE
Where to make API calls?

### ISSUE THREAD

**Issue by denny64** [satendra02/react-chrome-extension#16]
Where is an appropriate place to make API calls?

**Comment by satendra02** [comment]
Hi @denny64 

**App.js** is the entry point to your app means its a root component, Inside it, you can Include your other react component and use react lifecycle hooks or you can see I have used the `render` method of react component lifecycle in **App.js**. Similarly, you can use the `componentDidMount` method and call your API inside it and update HTML accordingly.

**Comment by denny64** [comment]
@satendra02 what is the difference between App.js and content.js? Why is App.js necessary when we only need to render the chrome extension?

**Comment by satendra02** [comment]
@denny64 

**content.js** is the entry of the chrome extension build and inside it, you can see there is a `Main` component which is rendering some HTML code. 

**App.js** is a separate component that you can use as a root component.  

Currently inside **content.js** I have created the `Main` component and written some HTML there inside `render` function. you can replace that HTML with  `<App  document={document} window={window}/>` and start writing you code inside **App.js**

> I am going to update it in documentation also

**Comment by denny64** [comment]
Thanks!

**Comment by satendra02** [comment]
Check at this comment on medium There I have explained its implementation.

https://medium.com/p/1c7c5082417d/responses/show
