### ISSUE TITLE
How to build material ui into production?

### ISSUE THREAD

**Issue by Blkc** [satendra02/react-chrome-extension#17]
I was using import statement like `import { makeStyles } from '@material-ui/core/styles'` and `import CircularProgress from '@material-ui/core/CircularProgress'` and it works fine in development and I can see that the style is being injected onto the page with an attribute of `data-jss`. 

![image](https://user-images.githubusercontent.com/7827466/74105483-1d461d80-4b2c-11ea-86a3-02cbfc79ca91.png)

But when I ran `npm run build` and the `content.css` does not include the styles and the page in production does not have the styles from material ui. I tried modifying the `webpack.config.prod.js` to use 

`test: /\.css$/,
            use: [{
              loader: MiniCssExtractPlugin.loader,
              options: {
                esModule: true,
              },
            },'css-loader']`

but that doesn't seem to work. Is there a solution? Thanks in advance.

**Comment by satendra02** [comment]
Hi @Blkc 
I need to debug why imported **CSS** not included in `content.css`. 
As a workaround  what you can do is keep the `materialui.css` file inside `public > css` folder and inject your CSS manually inside Iframe via `chrome.runtime.getURL` method
```
<Frame head={[<link type="text/css" rel="stylesheet" href={chrome.runtime.getURL("/css/materialui.css")} ></link>, <link type="text/css" rel="stylesheet" href={chrome.runtime.getURL("/static/css/content.css")} ></link>]}>
       <FrameContextConsumer>
             {
                 // Callback is invoked with iframe's window and document instances
                 ({document, window}) => {
                    // Render Children
                    return <App document={document} window={window} />
                 }
             }
       </FrameContextConsumer>
</Frame> 
```

**Comment by Blkc** [comment]
@satendra02 Thanks for the suggestion but I have a feeling it must be missing a loader or a having a misconfiguration issue

**Comment by skyfriends** [comment]
@RanaOsamaAsif 
I am having the same issue.  It seems kind of limited to imagine using React only with CSS.  One of the great things about the library is that there is a huge community of open sourced style libs like material-ui.  I was pretty excited when I started on this, but I think I need to scrap it at this point.
