### ISSUE TITLE
Content Security Policy issue

### ISSUE THREAD

**Issue by zenzjtech** [satendra02/react-chrome-extension#18]
Hello,

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-GgRxrVOKNdB4LrRsVPDSbzvfdV4UqglmviH9GoBJ5jk='". Either the 'unsafe-inline' keyword, a hash ('sha256-N/tHXVVQthcO77tcS7VT2tmLWxdumYi73F87h+hd5s0='), or a nonce ('nonce-...') is required to enable inline execution.`

My manifest.json - I tried both hashes: the default one, and the suggested in the error message, but none of them work.
```
{
  "name": "My Extension",
  "version": "1.0",
  "manifest_version": 2,
  "browser_action": {
    "default_popup": "index.html"
  },
  "content_security_policy": "script-src 'self' 'sha256-N/tHXVVQthcO77tcS7VT2tmLWxdumYi73F87h+hd5s0='; object-src 'self'"
}
````

**Comment by zenzjtech** [comment]
@satendra02 : I forgot to build after updating to the suggested hash. Just rebuild and now it work!

**Comment by zenzjtech** [comment]
Is there a away to fix the issue that whenever extension is rebuilt, then a new hash is required for **manifest.json**?
The extension keep signaling the above error.

**Comment by satendra02** [comment]
Hi @zenzjtech 

Do these steps and let me know if it works.

1. Create a .env file in the project root
2. Add variable as follows: **INLINE_RUNTIME_CHUNK=false**
3. Build the project again and load the extension again.

I hope it helps!
