### ISSUE TITLE
React components broken when rendered inside iframe

### ISSUE THREAD

**Issue by Tinyik** [satendra02/react-chrome-extension#19]
It seems a great deal of React UI components do not work properly when rendered using this technique inside iframe. Is there any way around it?

Things I have tested that do not work as expected inside iframe using the inject technique:
1. `react-beautiful-dnd`
2. `material-ui`
3. `react-rnd`

Thanks in advance!

**Comment by satendra02** [comment]
Hi @Tinyik

Check [my comment](https://github.com/satendra02/react-chrome-extension/issues/17#issuecomment-584011091) in this issue #17

**Comment by Tinyik** [comment]
Thank you I will try that for material ui. But in the case of
react-beautiful-dnd and react-rnd I feel the problem is not about styling
because the animation is broken. (e.g. all elements become un-draggable but
they have attributes set up correctly when viewed in html by the library).

I’m suspecting that the issue has to do with iframe’s window and document
conflicting with React’s global variable window and document referring to
the page which we inject into.

Is there a way to replace React’s global variable to use the one returned
from FrameContextConsumer?

Thanks!

**Comment by satendra02** [comment]
> Replacing the host page's `window` and `document` with iframe's one is not a good idea in that case host page's javascript will be affected. 

I got the same issue while using [antd](https://ant.design/components/tooltip/#API) library tooltip component. But they did a fabulous job by exposing `getPopupContainer` API where I can pass iframe's document.
````
<Tooltip title="Prompt text" getPopupContainer={()=>this.props.document.body}>
   <span>Tooltip will show on mouse enter.</span>
</Tooltip>
````
**Note:**  Use `this.props.document` to use Iframe's document.

I believe the library you are using must have such an API where you can pass the DOM container. If not you must fork that library and tweak into there code.

I hope that helps!

**Comment by satendra02** [comment]
Someone already opened the same issue in `react-rnd` library we are discussing 
https://github.com/bokuweb/react-rnd/issues/592

Also, check this issue comment in `react-beautiful-dnd` I believe it will help. 
https://github.com/atlassian/react-beautiful-dnd/issues/796#issuecomment-427736444

**Comment by Tinyik** [comment]
Thank you so much! I'm looking into the options now.
