### ISSUE TITLE
Make extension compatible with Create React App v2.x

### ISSUE THREAD

**Issue by satendra02** [satendra02/react-chrome-extension#2]
**`Error: Cannot find module './polyfills`'**

After running `yarn run eject`

**Comment by dianasaurio** [comment]
Awesome!! 🎉

**Comment by danielgwilson** [comment]
This is spot on but I still found it a bit confusing with create-react-app 2.1.1 ejected. For anyone else slightly confused:

There was no `require.resolve(./polyfills)` dependency.

Here's my `entry` in webpack.config.js (which appears to be the only config file now, no webpack.config.prod.js)

```javascript
entry: {
      app: [
        // Include an alternative client for WebpackDevServer. A client's job is to
        // connect to WebpackDevServer by a socket and get notified about changes.
        // When you save a file, the client will either apply hot updates (in case
        // of CSS changes), or refresh the page (in case of JS changes). When you
        // make a syntax error, this client will display a syntax error overlay.
        // Note: instead of the default WebpackDevServer client, we use a custom one
        // to bring better experience for Create React App users. You can replace
        // the line below with these two lines if you prefer the stock client:
        // require.resolve('webpack-dev-server/client') + '?/',
        // require.resolve('webpack/hot/dev-server'),
        isEnvDevelopment &&
          require.resolve("react-dev-utils/webpackHotDevClient"),
        // Finally, this is your app's code:
        paths.appIndexJs
        // We include the app code last so that if there is a runtime error during
        // initialization, it doesn't blow up the WebpackDevServer client, and
        // changing JS code would still trigger a refresh.
      ].filter(Boolean),
      content: "./src/content.js"
    },
```

I also had more `#.js` files in /static/js/ for whatever reason, so here's my extension's entry for `content_scripts` in the manifest:

```javascript
"content_scripts": [
    {
      "matches": ["https://google.com/"],
      "css": ["/static/css/app.css", "/static/css/content.css"],
      "js": ["/static/js/0.js", "/static/js/3.js", "/static/js/content.js"],
      "run_at": "document_end"
    }
  ],
```

**Comment by Romstar** [comment]
I believe this needs to be reopened for the latest version

**Comment by satendra02** [comment]
@Romstar Are you facing any kind of issue? Feel free to create a new issue for that with the error logs if you have any. 

I have updated webpack version #10 hope it will help.

**Comment by Romstar** [comment]
@satendra02 I have it working now but there were required changes.  For example, I don't have to do

```"content_scripts": [
    {
      "matches": ["https://google.com/"],
      "css": ["/static/css/app.css", "/static/css/content.css"],
      "js": ["/static/js/0.js", "/static/js/3.js", "/static/js/content.js"],
      "run_at": "document_end"
    }
  ],```

I believe I was able to change it to where there is only one output file.  I don't recall what I did as this was a month or so ago.  When I go through the code again I'll post an update here.  Also, there was a webpack change that required some research.

**Comment by satendra02** [comment]
@Romstar That's great to hear that you made it work for the latest version of `create react app`. I believe you are using version **3.x**

Please post the changes you did whenever you get time, It will help others if they face the same issue.

You can also create a pull request for the same I will definitely merge it to master 

Thanks

**Comment by MrGiga** [comment]
@danielgwilson  These changes result in the following error after `running yarn build`

> Cannot read property 'filter' of undefined

**Comment by carlosvq** [comment]
> @danielgwilson These changes result in the following error after running `yarn build`
> 
> > Cannot read property 'filter' of undefined

I have the same problem @danielgwilson

**Comment by carlosvq** [comment]
> These changes result in the following error after running `yarn build`

Hi @MrGiga , I had the same problem, to solve that, I did this configuration in my entry point:

```js
    entry: {
      main: [
        // Include an alternative client for WebpackDevServer. A client's job is to
        // connect to WebpackDevServer by a socket and get notified about changes.
        // When you save a file, the client will either apply hot updates (in case
        // of CSS changes), or refresh the page (in case of JS changes). When you
        // make a syntax error, this client will display a syntax error overlay.
        // Note: instead of the default WebpackDevServer client, we use a custom one
        // to bring better experience for Create React App users. You can replace
        // the line below with these two lines if you prefer the stock client:
        // require.resolve('webpack-dev-server/client') + '?/',
        // require.resolve('webpack/hot/dev-server'),
        isEnvDevelopment &&
          require.resolve("react-dev-utils/webpackHotDevClient"),
        // Finally, this is your app's code:
        paths.appIndexJs
        // We include the app code last so that if there is a runtime error during
        // initialization, it doesn't blow up the WebpackDevServer client, and
        // changing JS code would still trigger a refresh.
      ].filter(Boolean),
      content: "./src/content.js"
    },
```

This problem happened because `ManifestPlugin` tries to make a filter with the `main` field.

<img width="695" alt="Screen Shot 2019-11-28 at 11 23 11 AM" src="https://user-images.githubusercontent.com/14861369/69817674-8545c280-11d1-11ea-982c-4b426b202631.png">

To solve this, instead of `app`, use `main` to define your main entrypoint on the object as I showed you before.

**Comment by chrisstpierre** [comment]
This needs to be re-opened now for webpack 4.3.x, which looks like this:
```
entry: [
      // Include an alternative client for WebpackDevServer. A client's job is to
      // connect to WebpackDevServer by a socket and get notified about changes.
      // When you save a file, the client will either apply hot updates (in case
      // of CSS changes), or refresh the page (in case of JS changes). When you
      // make a syntax error, this client will display a syntax error overlay.
      // Note: instead of the default WebpackDevServer client, we use a custom one
      // to bring better experience for Create React App users. You can replace
      // the line below with these two lines if you prefer the stock client:
      // require.resolve('webpack-dev-server/client') + '?/',
      // require.resolve('webpack/hot/dev-server'),
      isEnvDevelopment &&
        require.resolve('react-dev-utils/webpackHotDevClient'),
      // Finally, this is your app's code:
      paths.appIndexJs,
      // We include the app code last so that if there is a runtime error during
      // initialization, it doesn't blow up the WebpackDevServer client, and
      // changing JS code would still trigger a refresh.
    ].filter(Boolean),
    output: {
```

**Comment by carlosvq** [comment]
Hey @chrisstpierre, you can convert it to an object like this:

```javascript
    entry: {
      main: [
        // Include an alternative client for WebpackDevServer. A client's job is to
        // connect to WebpackDevServer by a socket and get notified about changes.
        // When you save a file, the client will either apply hot updates (in case
        // of CSS changes), or refresh the page (in case of JS changes). When you
        // make a syntax error, this client will display a syntax error overlay.
        // Note: instead of the default WebpackDevServer client, we use a custom one
        // to bring better experience for Create React App users. You can replace
        // the line below with these two lines if you prefer the stock client:
        // require.resolve('webpack-dev-server/client') + '?/',
        // require.resolve('webpack/hot/dev-server'),
        isEnvDevelopment &&
          require.resolve("react-dev-utils/webpackHotDevClient"),
        // Finally, this is your app's code:
        paths.appIndexJs
        // We include the app code last so that if there is a runtime error during
        // initialization, it doesn't blow up the WebpackDevServer client, and
        // changing JS code would still trigger a refresh.
      ].filter(Boolean),
      content: "./src/content.js",
      background: "./src/background.js"
    },
```

I hope it helps :-)

**Comment by alphaq1205** [comment]
webpack.config.prod.js file missing after Ejecting create-react-app (npm run eject), my question from where I can set multiple entry points in webpack file.

**Comment by satendra02** [comment]
Hi @alphaq1205 

check above @danielgwilson [answer](https://github.com/satendra02/react-chrome-extension/issues/2#issuecomment-460014828) the file name must be `webpack.config.js` in the latest version.

**Comment by lucasgit2000** [comment]
> > These changes result in the following error after running `yarn build`
> 
> Hi @MrGiga , I had the same problem, to solve that, I did this configuration in my entry point:
> 
> ```js
>     entry: {
>       main: [
>         // Include an alternative client for WebpackDevServer. A client's job is to
>         // connect to WebpackDevServer by a socket and get notified about changes.
>         // When you save a file, the client will either apply hot updates (in case
>         // of CSS changes), or refresh the page (in case of JS changes). When you
>         // make a syntax error, this client will display a syntax error overlay.
>         // Note: instead of the default WebpackDevServer client, we use a custom one
>         // to bring better experience for Create React App users. You can replace
>         // the line below with these two lines if you prefer the stock client:
>         // require.resolve('webpack-dev-server/client') + '?/',
>         // require.resolve('webpack/hot/dev-server'),
>         isEnvDevelopment &&
>           require.resolve("react-dev-utils/webpackHotDevClient"),
>         // Finally, this is your app's code:
>         paths.appIndexJs
>         // We include the app code last so that if there is a runtime error during
>         // initialization, it doesn't blow up the WebpackDevServer client, and
>         // changing JS code would still trigger a refresh.
>       ].filter(Boolean),
>       content: "./src/content.js"
>     },
> ```
> 
> This problem happened because `ManifestPlugin` tries to make a filter with the `main` field.
> 
> <img alt="Screen Shot 2019-11-28 at 11 23 11 AM" width="695" src="https://user-images.githubusercontent.com/14861369/69817674-8545c280-11d1-11ea-982c-4b426b202631.png">
> 
> To solve this, instead of `app`, use `main` to define your main entrypoint on the object as I showed you before.

definitely a solution for the problem, you and @danielgwilson saved my day.

**Comment by lucasgit2000** [comment]
@carlosvq , definitely a solution for the problem, you and @danielgwilson saved my day. Thanks!

**Comment by Adrian-Samuel** [comment]
@lucasgit2000 @satendra02 @carlosvq @chrisstpierre 

Does anyone have a complete list of changes that they need to make to get this to work with the current ejection of npx create-react-app ejection?

I'm quite new to React and configuring webpack.config.js and matching it correctly to my manifest is quite confusing with the different answers above

**Comment by trozler** [comment]
Hi, 
I managed to follow the article and get it working with create-react-4.0.0, and I thought this might be useful for someone. 

These were the steps I took:

1. Alter `manifest.json` from article.
- Notice we need to include two hashes, these hashes may differ from your project; and chrome will explicitly tell you what hashes to include when you try to load your extension.
- We also include more js content scripts.
  "content_security_policy": "script-src 'self' 'sha256-NAAKFqXxfjI1LgmKrrc3nxKe0WeY4/Lkue3yXruT4OE=' 'sha256-UtdLJkZdXQ6adZtYaJY8FbnmuNwWtFQ7lkWJX2iMz8E='; object-src 'self'",
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "css": [
        "/static/css/main.chunk.css",
        "/static/css/content.chunk.css"
      ],
      "js": [
        "/static/js/0.chunk.js",
        "/static/js/5.chunk.js",
        "/static/js/content.chunk.js",
        "/static/js/runtime-content.js"
      ],
      "run_at": "document_end"
    }
  ],
```

2. Change `webpack.config.js`.
```
    entry: {
      main:
        isEnvDevelopment && !shouldUseReactRefresh
          ? [
              webpackDevClientEntry,
              paths.appIndexJs,
            ]
          : paths.appIndexJs,
      content:
        isEnvDevelopment && !shouldUseReactRefresh
          ? [webpackDevClientEntry, paths.appContentJs]
          : paths.appContentJs,
    },
```
- Notice we use `main`, not `app`. As pointed out by @carlosvq.


#### Note on cloning template:
When I tried to clone the template, I ran into a lot of errors when running `npm install`. So I instead just followed the article and ran the commands.

#### Note on create-react-app@4.0.0:
If you are using v4.0.0 there is currently a bug which occurs when you eject. A pull request has been [merged](https://github.com/facebook/create-react-app/pull/9885), but not been released as of November 13th 2020. So if you want to eject, [here](create-react-4.0.0) is a clean bug fix..
For future versions of create-react-app you should't have to worry about this.

**Comment by axelmierczuk** [comment]
I was running into an issue with:
`    entry: {
      main:
        isEnvDevelopment && !shouldUseReactRefresh
          ? [
              webpackDevClientEntry,
              paths.appIndexJs,
            ]
          : paths.appIndexJs,
      content:
        isEnvDevelopment && !shouldUseReactRefresh
          ? [webpackDevClientEntry, paths.appContentJs]
          : paths.appContentJs,
    },`

I needed to add:
**appContentJs: resolveModule(resolveApp, "src/content"),** 
to paths.js under module.exports. 
Everything works well with the instructions above. 
Hope this helps.

**Comment by willliuwillliu** [comment]
I'm trying the above steps from @trozler and @axelmierczuk, but am running into an error: ``INLINE_RUNTIME_CHUNK=false node scripts/build.js``, when I try the build step. Anyone know how to work around this? I'm using the latest version of CRA which I believe is v4.04
