### ISSUE TITLE
Assets in React app don't have extension's path

### ISSUE THREAD

**Issue by aargiriou** [satendra02/react-chrome-extension#21]
Hi,
It seems that any assets (image tags) inside the React App, will not have the extension's path.
```html
<img src="/static/media/logo.5d5d9eef.svg" class="App-logo" alt="logo">
```
![image](https://user-images.githubusercontent.com/8590753/80832132-c2850500-8bf4-11ea-9fc0-2d042cc7919c.png)

Is there a way with `webpack` to prefix the url links with the extension's url
like `chrome-extension://<extension_dynamic_code>`?
And also, can this `<extension_dynamic_code>` be dynamic somehow?

I have added in the `manifest.json` the asset dir:
```json
"web_accessible_resources":[
   "/static/media/*"
]
```
so that i can access the assets.

Great work by the way! Thanks a lot!

**Comment by satendra02** [comment]
Hi @aargiriou

Thanks for the heads up 👍

Actually the current code is the default of `create-react-app` and will work fine when you run the app with the web server in the browser, but for running it as an extension we need to make some config changes and some code.

I have created a pull request #22  for this.

Please take a pull of [asset-load-fix](https://github.com/satendra02/react-chrome-extension/tree/asset-load-fix) branch and follow the below steps to get it working

- Run `yarn build`
- Reload extension 

Let me know if this works I will merge it to master.

**Comment by aargiriou** [comment]
Yes it is working!
I hopped there was a way through webpack to prefix the absolute url in each case..
But nevertheless the `chrome.runtime.getURL()` works!
Thanks!
