### ISSUE TITLE
Reduce width of original webpage to accommodate extension

### ISSUE THREAD

**Issue by zhoujc999** [satendra02/react-chrome-extension#26]
Hi satendra02,
Thank you for providing an awesome tutorial and boilerplate! This might be a trivial question, but I was wondering if there is any way to reduce the width of the original webpage (make it narrower) to accommodate the extension instead of having the extension floating on the right (which covers the webpage)? Any directions or tips will be appreciated!

**Comment by bnitsan** [comment]
Hey, is there a suggestion on how to do this? 
Perhaps even control the width by dragging the border, e.g., as the Chrome console panel behaves?
Thanks!
