### ISSUE TITLE
Scraping Website from Extension

### ISSUE THREAD

**Issue by builtbyproxy** [satendra02/react-chrome-extension#27]
# Hello

Thanks a lot for helping me here: https://github.com/satendra02/react-chrome-extension/issues/24

Just wondering if I can get some advice on how I would use this module and set-up to scrape a webpage I've navigated to?

Ideally, I'd like to avoid JQuery or Cheerio however I am comfortable with it if that's the easiest way. 

Thanks a bunch

**Comment by satendra02** [comment]
Hi @builtbyproxy 

For scrapping webpages, there is a node.js package [node-readability](https://github.com/Tjatse/node-readability). I am using it and it works like charm. Give it a try 

However, Cheerio is a good option to go with.

**Comment by builtbyproxy** [comment]
How do you actually inject though and get the HTML to then parse into `node-readability`? 

Thanks a lot @satendra02

**Comment by builtbyproxy** [comment]
Thanks a lot @satendra02 
I gave it a go with node-readability and it's working a treat!
