### ISSUE TITLE
iFrame margin 8px

### ISSUE THREAD

**Issue by builtbyproxy** [satendra02/react-chrome-extension#28]
Hello
I'm currently injecting the following HTML into my page:
![image](https://user-images.githubusercontent.com/16897508/83493397-1470c180-a4f8-11ea-9e49-409f7ebc1c02.png)

![image](https://user-images.githubusercontent.com/16897508/83493522-3a966180-a4f8-11ea-9f18-181c0a8bef42.png)

However for some reason I'm automatically getting a margin of 8px applied to the iFrame

I realise this isn't from your plugin but have you experienced this before and if so how did you fix it?

**Comment by satendra02** [comment]
Hi @builtbyproxy 

Yes, Actually **iframe** HTML tag has a default margin of **8px** attached to it.
You need to override it in your `content.css`

```
body {
    padding: 0;
    margin: 0;
}
```

**Comment by builtbyproxy** [comment]
Phenomenal thanks a lot for this @satendra02 
Wasn't even aware of user agent styling!
