### ISSUE TITLE
Extension doesn't open on all pages.

### ISSUE THREAD

**Issue by hellofantastic** [satendra02/react-chrome-extension#30]
Great repo!
Just getting my feet wet with react and chrome Ext dev.

I cloned and setup this repo but noticed the side panel doesn't open on some webpages and right clicking and changing  this menu item in picture doesn't affect in those situations.
<img width="617" alt="Screen Shot 2020-06-07 at 9 29 11 AM" src="https://user-images.githubusercontent.com/6655746/83974314-63747900-a8a1-11ea-96eb-bc83d6a08d99.png">

Am I missing something? Again I just followed the instructions. 
Much appreciated

**Comment by hellofantastic** [comment]
OK so it will.. but on some pages you need to do a reload and on some page you don't need to reload  it just works. Is there a background auto reload that can happen or is this just a quirk that you get due to using this way instead of traditional popup?

**Comment by satendra02** [comment]
Hi @hellofantastic
Glad you liked the repo.

I didn't included auto injection code in this repo. Check this issue #7 for implementation.

**Comment by hellofantastic** [comment]
Ah... missed it in my search before posting. Most excellent. Thanks
