### ISSUE TITLE
Jest won't work out of the box

### ISSUE THREAD

**Issue by pmrt** [satendra02/react-chrome-extension#32]
Hi, first of all let me thank you for this CRA-based boilerplate. You've saved me so much time!

Now, straight to the point — There's a problem with the test script, `yarn test` won't work out the box. 

## Steps to reproduce

Clone this repository, run `yarn install` and try to run tests with `yarn test`, you'll run into two issues:

```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event on FSWatcher instance at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I thought it was a problem with not ignoring node_modules at first, but AFAIK jest ignores node_modules by default. So I solved this updating the `jest` package.

Then there's this one:

```
ReferenceError: [BABEL] /Users/<your-user>/Desktop/react-chrome-extension/config/polyfills.js: Unknown option: /Users/<your-user>/Desktop/react-chrome-extension/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.

    A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

    Invalid:
      `{ presets: [{option: value}] }`
    Valid:
      `{ presets: [['presetName', {option: value}]] }`

```

Which I solved updating the `babel-jest` package.

##  Solution (to sum up)

- Update `jest`and `babel-jest` packages.

**Comment by satendra02** [comment]
Hi @pmrt,

Thanks for reporting the issue and that's great you fixed it.
Please create a pull request and update the versions of these packages. I will merge it to master.

Thanks for your contribution.
