### ISSUE TITLE
Can't use "import" in public/app/background.js file

### ISSUE THREAD

**Issue by kehtolaulu** [satendra02/react-chrome-extension#36]
Hello!
I want to import some functions from other files. src files are built ok, so I can use import in them, but I can't do it in my background.js file.
`Uncaught SyntaxError: Cannot use import statement outside a module`
 Could you help me?

**Comment by satendra02** [comment]
Hi @kehtolaulu,

You can't import your **src** folder functions inside **background.js**. It is used by extension as background script. 

You must use [Chrome messaging API](https://developer.chrome.com/extensions/messaging) to send and receive data.  
I already used it in **background.js** to send message when user click extension icon and then received it in **content.js** to toggle the extension. Similarly you can send message to background.js from src folder.

Let me know if you need more help. Also if you haven't read [this article ](https://itnext.io/create-chrome-extension-with-reactjs-using-inject-page-strategy-137650de1f39) then go through it. Here I have explained in detail how things are working in this repo.
