### ISSUE TITLE
Extension not working on chrome new tab page

### ISSUE THREAD

**Issue by dvandervlag** [satendra02/react-chrome-extension#42]
**Describe the bug**
The extension is not doing anything/working on Chrome's 'New Tab' page, accessed by CMD/CTRL + T in the browser.

**To Reproduce**
1. Open Chrome Browser
2. CTRL + T
3. Try to open extension
4. Notice it does not work

**Expected behavior**
Expected extension to also work on the 'New Tab' screen.

**Desktop (please complete the following information):**
 - OS: Mac OS X (Latest version)
 - Browser: Chrome
 - Version: Latest version

**Comment by satendra02** [comment]
Hi @dvandervlag 

> To auto-load your content script on every tab on install without refreshing the tab check this issue #7 

This boilerplate is [injecting script](https://developer.chrome.com/extensions/content_scripts#functionality) into the host page to function and content scripts must specify [match patterns](https://developer.chrome.com/extensions/match_patterns).  Check  **manifest.json** file.

````
{
 "name": "My extension",
 ...
 "content_scripts": [
   {
     "matches": [ "<all_urls>" ],
     ...
   }
 ],
 ...
}
````
But on opening a new tab using (CTRL + T), it does'nt contain any URL so the extension will not open on that tab. You can use the extension as a [popup](https://developer.chrome.com/extensions/getstarted) if you wish to open it on a tab with no URL.

Hope this helps!
