### ISSUE TITLE
Can't seem to add SASS

### ISSUE THREAD

**Issue by brianlearn** [satendra02/react-chrome-extension#46]
Is there a straight forward way of adding SASS? Can't seem to get it to work.

Here is what I tried:

1. Change `src/app.css` to `src/app.scss` 
2. In app.js, change the import statement to `import './App.scss';`
3. In webpack.config.prod.js - add sass-loader (reference from [https://www.npmjs.com/package/sass-loader](https://www.npmjs.com/package/sass-loader))

```
{
    test: /\.s[ac]ss$/,
    use: [
      // Creates `style` nodes from JS strings
      require.resolve('style-loader'),
      // Translates CSS into CommonJS
      require.resolve('css-loader'),
      // Compiles Sass to CSS
      require.resolve('sass-loader'), 
    ],
},
```
Result : Extension popup doesn't have any styling applied.

**Comment by sshulin** [comment]
I guess it was a problem with "style-loader". I tried ( #47 ) to use MiniCssExtractPlugin.loader as in css rule instead and it worked.
`
{
  test: /\.s[sc]ss$/,
  use: [
    {loader: MiniCssExtractPlugin.loader},
    require.resolve('css-loader'),
    require.resolve('sass-loader')
  ]
},
`

**Comment by satendra02** [comment]
Hey @sshulin 

That's great, Thanks for the PR. It's a big relief.

@brianlearn Try the suggested changes in PR(#47) and let me know if this works for you?

**Comment by brianlearn** [comment]
Yep it works! Thanks so much @sshulin!

What was your trouble shooting process that made you realize it was a problem with style-loader and that MiniCssExtractPlugin.loader would work instead?

**Comment by sshulin** [comment]
To be honest at first I tried to do it the whole other way just by adding node-sass and importing .scss file as is. But then I figured out, that build is more complicated and custom, so I looked for css part of build scripts (cause scss compiles in css afterall), found css rule, and checked for differences between it and your rule
