### ISSUE TITLE
Unwanted styling leaking into iframe

### ISSUE THREAD

**Issue by brianlearn** [satendra02/react-chrome-extension#48]
**Issue**
Some websites have CSS like `div {margin: 5em auto;}` which targets all of the divs that are injected into the website.

**Example**
The best example of a real-world website where this is happening is http://example.com, which shows that the styling from the website is overriding the styling inside of the iframe (below).

**Extension working nominally on google.com**
![image](https://user-images.githubusercontent.com/26777755/97462314-ccfe2e00-18fb-11eb-9ca6-1d0150255da3.png)

**Extension styling breaking on example.com**
![image](https://user-images.githubusercontent.com/26777755/97461709-3af62580-18fb-11eb-9473-cfa49c641805.png)

**Plausible Fix**
I'm pretty sure the only way to fix this universally is to implement a shadow dom.

Thoughts?

**Comment by satendra02** [comment]
Hi @brianlearn 

Yes, of course, shadow dom sounds like a good idea. But I haven't got a chance to do experiment with it.
Need to check the feasibility, if we can pass the host page document to shadow dom as props, As we are doing with IFrame for accessing host page content inside the extension.

Actually, I am really busy with some of my other projects so don't have time to look into it. It will be great if you can create PR for that.

**Comment by 9267aakashsharma** [comment]
I tried shadow DOM, the css is still leaking.
