### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by mqasim1990** [satendra02/react-chrome-extension#5]
I am using npm 
just following your instructions
running `npm run build` but its giving an error
`Module build failed: BrowserslistError: Unknown browser query `dead`
    at Array.forEach (<anonymous>)`

Full Error log
`./src/content.css
Module build failed: BrowserslistError: Unknown browser query `dead`
    at Array.forEach (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-extension@0.1.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-extension@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by satendra02** [comment]
@mqasim1990 I found a StackOverflow thread regarding the same
[https://stackoverflow.com/questions/52939103/browserslisterror-unknown-browser-query-dead-in-react-express-app](https://stackoverflow.com/questions/52939103/browserslisterror-unknown-browser-query-dead-in-react-express-app)

Hope this helps
