### ISSUE TITLE
Can we turn this off when running the app from `yarn start`? Failed to compile - No unused vars 

### ISSUE THREAD

**Issue by lancesnider** [satendra02/react-chrome-extension#54]
When you include an unused var, the app fails to compile and you get the following error: 

```
Failed to compile
./src/components/sidebar/CurrentProduct.js
  Line 1:27:  'useEffect' is defined but never used  no-unused-vars

Search for the keywords to learn more about each error.
```

That's great for a production build, but while working, it'd be nice to just see the warning but still be able to run the app. This is especially true when running the app from `yarn start`, rather than `yarn watch`. 

Updating the package.json to ignore the issue doesn't help: 

```
"eslintConfig": {
	"rules": {
		"no-unused-vars": "off"
	}
}
```

Thanks!

**Comment by satendra02** [comment]
Hey @lancesnider

It seems more of a programming error to me.  `useEffect` is a build-in react hook. I believe you must be using react version `>= 16.8.0` 

Try 'eslint-plugin-react' to ignore `no-unused-vars` errors.
https://stackoverflow.com/a/42542068/3404994

**Comment by lancesnider** [comment]
Thanks. Yeah, I ended up just adding `"no-unused-vars": "warn"` to `rules` in .eslintrc.
