### ISSUE TITLE
Is there a way by which I can keep the dev server running and it builds the changes directly into an html file which I can load in chrome ?

### ISSUE THREAD

**Issue by rohankeskar19** [satendra02/react-chrome-extension#57]
I want to know if  there is a way by which I can keep coding in react and on each file save it will build the app into an html file then I just hit the refresh button in chrome and it reloads the html and then my content script will just inject a iframe into the page and set the src to the html file which is getting built from react?

**Comment by satendra02** [comment]
Hi @rohankeskar19 

Check this issue #8 It might help.
