### ISSUE TITLE
Just want to know how click event will work

### ISSUE THREAD

**Issue by chintan-avnio** [satendra02/react-chrome-extension#61]
`/*
    * For openning the Hamburger Menu
    */
   openMenu(){
        var element = document.getElementById("body");
        element.classList.toggle("menu-open");
    }
`

`<div className="menu-icon" onClick={() => this.openMenu()}>
                            <div className="menu-box">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </div>`

Used above code! in component named as header.js which is included in app.js

"document.getElementById("body");" Hopefully this line should access the iframe's body but that;s not the case it is catching the main page's body!

Thanks in advance!

**Comment by satendra02** [comment]
Hi @chintan-avnio 

You can see I am passing `document` and `window` as props to **App** component in the `content.js` file, so Inside App you must use `props.document` instead `document` to access iframe DOM.
```
this.props.document.getElementById("body");
```
