### ISSUE TITLE
Migration to Manifest V3?

### ISSUE THREAD

**Issue by willliuwillliu** [satendra02/react-chrome-extension#63]
Hi! New chrome extension developer here. As I've been learning to develop chrome extensions, I'm reading about the migration to Manifest V3 and was wondering if there are plans to migrate this repo. 

Additionally, this repo is still built using older versions of CRA that been ejected. I noticed in newer versions the config folder looks very different. Are there any anticipated issues if I build an extension on these older files? 

Hopefully in the near future I will be able to contribute to the migration of this repo to Manifest V3 once I have learned enough, but wanted to leave this note here to see if anyone else has been thinking about this!

**Comment by satendra02** [comment]
Hi @willliuwillliu 

For now, I don't have any plans to upgrade the repo to Manifest V3 as I am super busy with my other projects. 

But it will be great if you can contribute to this repo, looking forward to it.

Thanks

**Comment by thisisnotawill** [comment]
Hi @satendra02, could I ask that you delete your previous comment or edit out my old username? I have changed my github username and am trying to remove references to the previous name. Thanks so much!

**Comment by satendra02** [comment]
Repo is upgraded to support Manifest V3 https://github.com/satendra02/react-chrome-extension/pull/97
