### ISSUE TITLE
SHA code in content_security_policy of the manifest

### ISSUE THREAD

**Issue by UnsterblichDK** [satendra02/react-chrome-extension#76]
Could you please advise what file was coded in SHA in the following line of the manifest?

- "content_security_policy": "script-src 'self' 'sha256-GgRxrVOKNdB4LrRsVPDSbzvfdV4UqglmviH9GoBJ5jk='

After making changes to the extension, it's giving errors when trying to load the extension to chrome. 
Thanks!

P.S. removing it still allows the extension to run, so I wonder if that's even needed.

**Comment by satendra02** [comment]
@UnsterblichDK Please refer this [issue comment](https://github.com/satendra02/react-chrome-extension/issues/18#issuecomment-598695840). I have explained `content_security_policy` in little detail there.
