### ISSUE TITLE
Access chrome object (in this case for current tab URL from any component)?

### ISSUE THREAD

**Issue by chillbert** [satendra02/react-chrome-extension#77]
I have this in my content.js component:

```
  useEffect(() => {
    const queryInfo = { active: true, lastFocusedWindow: true };
    chrome.tabs &&
      chrome.tabs.query(queryInfo, (tabs) => {
        const url = tabs[0].url || "";
        alert(url)
      });
  }, [])
```

the alert does not get fired. How can I access tabs in content.js (or any components which I import into content.js)?

manifest.json includes already the right permissions:
```

  "permissions": [
    "tabs",
     "activeTab",
     "<all_urls>"
 ],
```

**Comment by satendra02** [comment]
You must add  `/*global chrome*/` at the top of the React component file to access chrome inside component.
