### ISSUE TITLE
how to use this with hot reloader

### ISSUE THREAD

**Issue by whatsdis** [satendra02/react-chrome-extension#8]
its a pain to wait 50+ seconds for each build to complete just to see the changes I made, my app has a lot of components.

what can I do to speed up development?

**Comment by satendra02** [comment]
I found some packages that will help you to hot reload your chrome extension while developing.

1. Chrome Extension Hot Reloader.  [xpl/crx-hotreload](https://github.com/xpl/crx-hotreload?source=post_page-----574fc879356e----------------------)
2. Hot reloading while developing Chrome extensions with webpack 🔥 [rubenspgcavalcante/webpack-chrome-extension-reloader](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader?source=post_page-----574fc879356e----------------------)

**Note:** I haven't used any of these, Please let me know if this helps and share your learning.

**Comment by frontr-uk** [comment]
does are for webpack, but the project is not built to support webpack

**Comment by lancesnider** [comment]
1. The problem with xpl/crx-hotreload is `fs.emptyDirSync(paths.appBuild);` in build.js. When it removes everything in that folder, it hot reloads, but without all the necessary files. When that happens, Chrome disables the extension. 

2. There's a new link for the other one you posted: https://github.com/rubenspgcavalcante/webpack-extension-reloader, but I can't seem to understand the docs. 😬  Anyone else have success with that one?

**Comment by lancesnider** [comment]
Okay, I have a decent-ish solution to make crx-hotreload work. Note, this causes a complete refresh of the extension, not a hot module reload. 

1. Copy the hot-reload.js (https://github.com/xpl/crx-hotreload/blob/master/hot-reload.js) into the `public` directory. 
2. Create a new function in hot-reload.js that'll delay the reload, giving a bit of time between deleting everything and copying the updated files over. Update the time if needed. 
```js
const waitToReload = () => {
    setTimeout(() => {
        reload();
    }, 2000);
}
```
3. Inside the `watchChanges`function, change `reload()` to `waitToReload()`
4. In manifest.json, add the `hot-reload.js` script under background scripts: 
```js
"background": {
    "scripts": [
      "app/background.js",
      "hot-reload.js"
    ]
  },
```
5. Go to chrome://extensions and refresh your extension. 

Now every time you make a change, it'll wait a couple of seconds then refresh.

**Comment by satendra02** [comment]
Awesome @lancesnider, Thanks for your contribution.
