### ISSUE TITLE
Update to Manifest V3

### ISSUE THREAD

**Issue by darkshredder** [satendra02/react-chrome-extension#80]
**Describe the bug**
Update to Manifest V3

**Comment by satendra02** [comment]
Hi @darkshredder,  
Check this issue #2 comments it will help you to upgrade in the right direction. Also, It will be great if you can create PR for that.

**Comment by BhuveshDhiman** [comment]
Hi @darkshredder Were you able to upgrade to Manifest V3?

**Comment by dhimanAbhi** [comment]
I would like to contribute, can anyone assign me this issue?

**Comment by satendra02** [comment]
Hi @dhimanAbhi, Any update on this? You can directly create PR

**Comment by dovigz** [comment]
https://github.com/satendra02/react-chrome-extension/pull/97

**Comment by satendra02** [comment]
Thanks, @dovigz 

PR #97 merged to master.
