### ISSUE TITLE
`yarn start` failing

### ISSUE THREAD

**Issue by samuelkubai** [satendra02/react-chrome-extension#9]
Hi @satendra02, been using your boilerplate template to start on a new chrome extension. But running `yarn start` fails with the error: 

```bash
Cannot read property 'entryOption' of undefined
```
*Steps to reproduce it*
1. Clone this repository
2. Run `yarn`
3. Run `yarn start`

Is there a way I can get around this?

Please find attached a screenshot of the same.
![Screenshot 2019-09-16 10 53 14](https://user-images.githubusercontent.com/10863328/64941811-4067ec00-d870-11e9-9e05-b9578f1250fa.png)

**Comment by satendra02** [comment]
Hi @samuelkubai 

Thanks for reporting the issue.

Actually some of the dependencies are outdated and conflicting with webpack3. So I have upgraded webpack version from 3 to 4.

I have created a [pull request](https://github.com/satendra02/react-chrome-extension/pull/10) for this.

Please take a pull of **webpack4** branch and follow below steps to get it working

1. Delete old **node_modules** folder
2. Run `yarn install`
3. Run `yarn start`

Let me know if this works I will merge it to master.

**Comment by satendra02** [comment]
Hi @samuelkubai,

Pull request #10 is merged to **master** you can clone the repository again and follow _ReadMe_  to get it working.
